# on push to main branch and on pull request to main branch, build and test and commit to developmnet branch
name: Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      # - name: Test
      #   run: npm test
      - name: Commit to development branch
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Build and test"
          add: "build"
          branch: "development"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}